POST http://localhost:3005/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibWFya2NoaW5hQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2MTk5NTg5LCJleHAiOjE3NTYyMDMxODksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.nEC38Fm94JiyhVkXKWG8ZBR7-VDZcqshRdHY6rB9Hb0

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTc1NjE5OTU4OSwiZXhwIjoxNzU2Mjg1OTg5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.sAdf2856k905xp8v4t_pTJVudFf3BmUyT94Wb6EjOx4"
}